// src/protocol/opcodes.rs

//! MTGO protocol opcode and MagicProperty constants.
//!
//! Opcodes sourced from opcode-table.tsv (generated by tools/opcode-dump).
//! MagicProperty constants sourced from PROTOCOL_RESEARCH.md.

// === FLS-level opcodes (Level 1 messages) ===

pub const GS_CONNECT: u16 = 1024;
pub const GSH_GAME_STATUS_CHANGE: u16 = 1145;
pub const GS_MESSAGE: u16 = 1153;
pub const GS_PLAYER_ORDER: u16 = 1155;
pub const GS_REPLAY_MESSAGE: u16 = 1156;

// === Game-level opcodes (Level 2, inside MetaMessage) ===

pub const GAME_RESULTS: u16 = 4485;
pub const GAME_OVER: u16 = 4632;
pub const GAME_NEXT_STEP: u16 = 4643;
pub const NEW_CARD_ACTION: u16 = 4645;
pub const CARD_ACTION: u16 = 4647;
pub const GAME_PLAY_STATUS: u16 = 4652;
pub const V3_REPLAY_USER_ORDER: u16 = 4689;

// === MagicProperty keys (ThingElement attributes, bits 26-0) ===

pub const THINGNUMBER: u32 = 537878017;
pub const ZONE: u32 = 537878532;
pub const CONTROLLER: u32 = 537875729;
pub const OWNER: u32 = 537876535;
pub const CARDTEXTURE_NUMBER: u32 = 537875724;
pub const CARDNAME_STRING: u32 = 1074900499;
pub const TAPPED: u32 = 538063116;
pub const ATTACKING: u32 = 537874697;
pub const BLOCKING: u32 = 538214407;
pub const POWER: u32 = 538054425;
pub const TOUGHNESS: u32 = 538065157;
pub const DAMAGE: u32 = 537876480;
pub const SUMMONING_SICK: u32 = 537877508;
pub const FACE_DOWN: u32 = 537924114;
pub const ATTACHED_TO_ID: u32 = 538318848;
pub const IS_TOKEN: u32 = 537876520;
pub const PLUS_ONE_PLUS_ONE_COUNTERS: u32 = 538054419;
pub const MINUS_ONE_MINUS_ONE_COUNTERS: u32 = 538285849;
pub const LOYALTY_COUNTERS: u32 = 538075911;
pub const SRC_THING_ID: u32 = 537877505;

// === StateElementType ===

pub const STATE_ELEM_INVALID: u32 = 0;
pub const STATE_ELEM_CARD: u32 = 1;
pub const STATE_ELEM_PLAYER_STATUS: u32 = 2;
pub const STATE_ELEM_TURN_STEP: u32 = 3;
pub const STATE_ELEM_MANA_POOL: u32 = 4;
pub const STATE_ELEM_THING: u32 = 5;
pub const STATE_ELEM_ANIMATION: u32 = 6;
pub const STATE_ELEM_DAMAGE_ASSIGNMENT: u32 = 7;
pub const STATE_ELEM_CASUAL_WISH: u32 = 8;
pub const STATE_ELEM_CREATURE_ORDERING: u32 = 9;
pub const STATE_ELEM_INTERACT_STATE: u32 = 10;
pub const STATE_ELEM_COMMANDER_INFO: u32 = 11;
pub const STATE_ELEM_AUTO_YIELD_INFO: u32 = 12;
pub const STATE_ELEM_DUNGEON_INFO: u32 = 13;
pub const STATE_ELEM_MINI_CHANGE: u32 = 200;

// === PropertyContainer type tags (bits 31-27) ===

pub const PROP_TYPE_INT8: u32 = 0x20000000;
pub const PROP_TYPE_INT32: u32 = 0x28000000;
pub const PROP_TYPE_STRING: u32 = 0x40000000;
pub const PROP_TYPE_LIST: u32 = 0x08000000;
pub const PROP_TYPE_FUNCTION: u32 = 0x10000000;
pub const PROP_TYPE_STRING_CONSTANT: u32 = 0x48000000;
pub const PROP_TYPE_MASK: u32 = 0xF8000000;
pub const PROP_KEY_MASK: u32 = 0x07FFFFFF;

// === GamePlayStatusMessage flag bits ===

pub const FLAG_GAMESTATE_CONTAINS_DIFFS: u8 = 0x01;
pub const FLAG_GAMESTATE_HEAD: u8 = 0x02;
pub const FLAG_GAMESTATE_TAIL: u8 = 0x04;

// === Checksum ===

pub const CHECKSUM_SEED: i32 = 826366246;
